enyo.depends(
	"custom",
	"CheckboxItemControl.js",
	"SearchIndexViewControl.js",
	"HeaderControl.js",
	"InputItemControl.js",
	"PickerItemShortControl.js", 
	"PickerItemLabelEndControl.js",
	"PickerItemControl.js" 
);