enyo.depends(
	"Alert.js",
	"Confirm.js",
	"Focusable.js",
	"Notification.js",
 	"GMap.js",
 	"HNumPicker.js",
	"HDialPicker.js",
	"IconButton.js",
	"StateButton.js",
	"CartPrice.js",
	"ItemImageView.js",
	"NativeSelect.js",
	"Scroller.js"
);