enyo.kind({
    name: "AttendGroup",
    kind: "Control",
    classes:"mct-inputBoxGroup",
    components:[
        {
            kind:"Group",
            name:"txtGroup",
            components:[
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    active:true,
                    content:"Adam",
                    value:1
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Ammy",
                    value:2
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Andrew",
                    value:3
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Bryan",
                    value:4
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Claressa",
                    value:5
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Henry",
                    value:6
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Janice",
                    value:7
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Jessly",
                    value:8
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Leon",
                    value:9
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Phoebe",
                    value:10
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Tony",
                    value:11
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Vernon",
                    value:12
                },
                {
                    kind:"Button",
                    classes:"pickerLikeButton",
                    content:"Others",
                    value:13
                }
            ]
        }
    ],
    published:{
        active:0        
    },
    create: function() {
        this.inherited(arguments);
        this.activeChanged();
    },
    activeChanged:function() {
        this.$.txtGroup.setActive(this.$.txtGroup.controls[this.getActive()]);
        this.$.txtGroup.render();
    },
    getValue:function() {
        return this.$.txtGroup.getActive().value;
    }
});